### ISSUE TITLE
revamp scroll to cursor

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/actualvim#62]
Will fix these:
- [ ] #47 sometimes scrolls to top on revert file
- [ ] #46 cursor scroll doesn't happen left/right
- [ ] #42 scrolling to show cursor can end up in awkward spot

**Comment by lunixbochs** [comment]
still not fixed left-right
